name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Set secrets in Cloudflare
        run: |
          echo "${{ secrets.TELEGRAM_BOT_TOKEN }}" | wrangler secret put TELEGRAM_BOT_TOKEN --name cloudwork
          echo "${{ secrets.WORKER_URL }}" | wrangler secret put WORKER_URL --name cloudwork
          echo "${{ secrets.WS_API_KEY }}" | wrangler secret put WS_API_KEY --name cloudwork
          echo "${{ secrets.ETH_MERCHANT_WALLET }}" | wrangler secret put ETH_MERCHANT_WALLET --name cloudwork
          echo "${{ secrets.TON_MERCHANT_WALLET }}" | wrangler secret put TON_MERCHANT_WALLET --name cloudwork
          echo "${{ secrets.PAYMENT_SERVERS }}" | wrangler secret put PAYMENT_SERVERS --name cloudwork
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy to Cloudflare
        run: wrangler deploy --name cloudflarewebworker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
