name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Set secrets in Cloudflare
        run: |
          echo "${{ secrets.TELEGRAM_BOT_TOKEN }}" | wrangler secret put TELEGRAM_BOT_TOKEN --yes
          echo "${{ secrets.WORKER_URL }}" | wrangler secret put WORKER_URL --yes
          echo "${{ secrets.WS_API_KEY }}" | wrangler secret put WS_API_KEY --yes
          echo "${{ secrets.ETH_MERCHANT_WALLET }}" | wrangler secret put ETH_MERCHANT_WALLET --yes
          echo "${{ secrets.TON_MERCHANT_WALLET }}" | wrangler secret put TON_MERCHANT_WALLET --yes
          echo "${{ secrets.PAYMENT_SERVERS }}" | wrangler secret put PAYMENT_SERVERS --yes
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy to Cloudflare
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
